--ENUMERACIONES

CREATE TYPE advising_modality AS ENUM ('classroom', 'virtual', 'hybrid');
CREATE TYPE alert_type AS ENUM ('academic_risk', 'high_load');
CREATE TYPE course_category AS ENUM ('general_studies', 'common', 'faculty', 'elective');
CREATE TYPE curriculum_simulation_status AS ENUM ('planned', 'simulated_completed', 'simulated_available');
CREATE TYPE enrollment_status AS ENUM ('active', 'withdrawn', 'completed');
CREATE TYPE prerequisite_type AS ENUM ('course', 'completed_cycle');
CREATE TYPE representative_position AS ENUM ('delegate', 'subdelegate');
CREATE TYPE student_course_status AS ENUM ('in_progress', 'approved', 'failed', 'withdrawn');
CREATE TYPE student_specialty_type AS ENUM ('primary', 'interest');

--TABLAS

CREATE TABLE app_user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  institutional_email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);


CREATE TABLE career (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  faculty VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE teacher (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_code VARCHAR(50) UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  institutional_email VARCHAR(150) UNIQUE
);


CREATE TABLE curriculum (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  career_id INTEGER NOT NULL UNIQUE REFERENCES career(id),
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_curriculum_id_career UNIQUE (id, career_id)
);


CREATE TABLE student (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES app_user(id),
  career_id INTEGER NOT NULL,
  curriculum_id INTEGER NOT NULL,
  current_level INTEGER,
  specialty_setup_completed BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_student_id_career UNIQUE (id, career_id),
  CONSTRAINT uq_student_id_curriculum UNIQUE (id, curriculum_id),
  CONSTRAINT chk_student_current_level CHECK (current_level IS NULL OR current_level BETWEEN 1 AND 10)
);


CREATE TABLE specialty (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  career_id INTEGER NOT NULL REFERENCES career(id),
  name VARCHAR(120) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_specialty_career_name UNIQUE (career_id, name)
);


CREATE TABLE student_specialty (
  student_id INTEGER NOT NULL REFERENCES student(id),
  specialty_id INTEGER NOT NULL REFERENCES specialty(id),
  selection_type student_specialty_type NOT NULL DEFAULT 'interest',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (student_id, specialty_id)
);


CREATE TABLE course (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  default_credit INTEGER NOT NULL,
  origin_faculty VARCHAR(120),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_course_default_credit CHECK (default_credit > 0)
);




CREATE TABLE curriculum_course (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculum_id INTEGER NOT NULL REFERENCES curriculum(id),
  course_id INTEGER NOT NULL REFERENCES course(id),
  cycle INTEGER NOT NULL,
  display_order INTEGER NOT NULL,
  credit INTEGER NOT NULL,
  category course_category NOT NULL DEFAULT 'faculty',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_curriculum_course UNIQUE (curriculum_id, course_id),
  CONSTRAINT uq_curriculum_course_id_curriculum UNIQUE (id, curriculum_id),
  CONSTRAINT chk_curriculum_course_cycle CHECK (cycle > 0),
  CONSTRAINT chk_curriculum_course_display_order CHECK (display_order > 0),
  CONSTRAINT chk_curriculum_course_credit CHECK (credit > 0)
);




CREATE TABLE curriculum_course_specialty (
  curriculum_course_id INTEGER NOT NULL REFERENCES curriculum_course(id),
  specialty_id INTEGER NOT NULL REFERENCES specialty(id),
  PRIMARY KEY (curriculum_course_id, specialty_id)
);


CREATE TABLE course_prerequisite (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculum_id INTEGER NOT NULL REFERENCES curriculum(id),
  curriculum_course_id INTEGER NOT NULL REFERENCES curriculum_course(id),
  prerequisite_type prerequisite_type NOT NULL,
  prerequisite_curriculum_course_id INTEGER REFERENCES curriculum_course(id),
  required_cycle INTEGER,
  CONSTRAINT chk_course_prerequisite_required_cycle CHECK (required_cycle IS NULL OR required_cycle > 0),
  CONSTRAINT chk_course_prerequisite_not_self CHECK (prerequisite_curriculum_course_id IS NULL OR curriculum_course_id <> prerequisite_curriculum_course_id),
  CONSTRAINT chk_course_prerequisite_kind CHECK (
      (prerequisite_type = 'course' AND prerequisite_curriculum_course_id IS NOT NULL AND required_cycle IS NULL)
      OR
      (prerequisite_type = 'completed_cycle' AND prerequisite_curriculum_course_id IS NULL AND required_cycle IS NOT NULL)
  )
);


CREATE TABLE student_curriculum_simulation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES student(id),
  curriculum_id INTEGER NOT NULL REFERENCES curriculum(id),
  curriculum_course_id INTEGER NOT NULL REFERENCES curriculum_course(id),
  status curriculum_simulation_status NOT NULL,
  CONSTRAINT uq_student_curriculum_simulation UNIQUE (student_id, curriculum_course_id)
);


CREATE TABLE academic_period (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_academic_period_dates CHECK (start_date < end_date)
);


CREATE TABLE course_offering (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_period_id INTEGER NOT NULL REFERENCES academic_period(id),
  course_id INTEGER NOT NULL REFERENCES course(id),
  CONSTRAINT uq_course_offering UNIQUE (academic_period_id, course_id)
);


CREATE TABLE syllabus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_offering_id INTEGER NOT NULL UNIQUE REFERENCES course_offering(id),
  title VARCHAR(150),
  drive_file_id VARCHAR(120) NOT NULL UNIQUE,
  drive_file_url VARCHAR(255) NOT NULL
);


CREATE TABLE section (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_offering_id INTEGER NOT NULL REFERENCES course_offering(id),
  teacher_id INTEGER NOT NULL REFERENCES teacher(id),
  code VARCHAR(30) NOT NULL,
  CONSTRAINT uq_section_offering_code UNIQUE (course_offering_id, code),
  CONSTRAINT uq_section_id_offering UNIQUE (id, course_offering_id)
);


CREATE TABLE enrollment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES student(id),
  section_id INTEGER NOT NULL REFERENCES section(id),
  status enrollment_status NOT NULL DEFAULT 'active',
  attended_hours NUMERIC(5,2) NOT NULL DEFAULT 0,
  absent_hours NUMERIC(5,2) NOT NULL DEFAULT 0,
  total_hours NUMERIC(5,2) NOT NULL DEFAULT 0,
  CONSTRAINT uq_enrollment_student_section UNIQUE (student_id, section_id),
  CONSTRAINT uq_enrollment_id_section UNIQUE (id, section_id),
  CONSTRAINT chk_enrollment_attended_hours CHECK (attended_hours >= 0),
  CONSTRAINT chk_enrollment_absent_hours CHECK (absent_hours >= 0),
  CONSTRAINT chk_enrollment_total_hours CHECK (total_hours >= 0),
  CONSTRAINT chk_enrollment_attendance_hours CHECK (attended_hours + absent_hours <= total_hours)
);


CREATE TABLE student_course_progress (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES student(id),
  curriculum_id INTEGER NOT NULL REFERENCES curriculum(id),
  curriculum_course_id INTEGER NOT NULL REFERENCES curriculum_course(id),
  status student_course_status NOT NULL,
  CONSTRAINT uq_student_course_progress UNIQUE (student_id, curriculum_course_id)
);


CREATE TABLE section_representative (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id INTEGER NOT NULL REFERENCES section(id),
  enrollment_id INTEGER NOT NULL UNIQUE REFERENCES enrollment(id),
  position representative_position NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE academic_week (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_period_id INTEGER NOT NULL REFERENCES academic_period(id),
  week_number INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  CONSTRAINT uq_academic_week_period_number UNIQUE (academic_period_id, week_number),
  CONSTRAINT chk_academic_week_number CHECK (week_number > 0),
  CONSTRAINT chk_academic_week_dates CHECK (start_date <= end_date)
);


CREATE TABLE schedule_session (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id INTEGER NOT NULL REFERENCES section(id),
  day_of_week INTEGER NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  classroom VARCHAR(100),
  color_hex VARCHAR(20),
  CONSTRAINT uq_schedule_session UNIQUE (section_id, day_of_week, start_time),
  CONSTRAINT chk_schedule_session_day CHECK (day_of_week BETWEEN 1 AND 7),
  CONSTRAINT chk_schedule_session_time CHECK (start_time < end_time)
);


CREATE TABLE course_advising_session (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_offering_id INTEGER NOT NULL REFERENCES course_offering(id),
  section_id INTEGER REFERENCES section(id),
  teacher_id INTEGER NOT NULL REFERENCES teacher(id),
  day_of_week INTEGER NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  classroom VARCHAR(100),
  meeting_url VARCHAR(255),
  modality advising_modality NOT NULL DEFAULT 'hybrid',
  note TEXT,
  CONSTRAINT chk_course_advising_day CHECK (day_of_week BETWEEN 1 AND 7),
  CONSTRAINT chk_course_advising_time CHECK (start_time < end_time)
);


CREATE TABLE assessment_type (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  abbreviation VARCHAR(30),
  description TEXT
);


CREATE TABLE assessment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  syllabus_id INTEGER NOT NULL REFERENCES syllabus(id),
  assessment_type_id INTEGER NOT NULL REFERENCES assessment_type(id),
  code VARCHAR(30) NOT NULL,
  name VARCHAR(150) NOT NULL,
  week_number INTEGER NOT NULL,
  weight NUMERIC(5,2) NOT NULL,
  CONSTRAINT uq_assessment_syllabus_code UNIQUE (syllabus_id, code),
  CONSTRAINT chk_assessment_week_number CHECK (week_number > 0),
  CONSTRAINT chk_assessment_weight CHECK (weight > 0 AND weight <= 100)
);


CREATE TABLE student_score (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id INTEGER NOT NULL REFERENCES enrollment(id),
  assessment_id INTEGER NOT NULL REFERENCES assessment(id),
  value NUMERIC(5,2),
  CONSTRAINT uq_student_score UNIQUE (enrollment_id, assessment_id),
  CONSTRAINT chk_student_score_value CHECK (value IS NULL OR value BETWEEN 0 AND 20)
);


CREATE TABLE announcement (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_representative_id INTEGER NOT NULL REFERENCES section_representative(id),
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  published_at TIMESTAMP NOT NULL DEFAULT now(),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);


CREATE TABLE alert (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES student(id),
  type alert_type NOT NULL,
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);


## Indices y restricciones complementarias relevantes


CREATE UNIQUE INDEX uq_academic_period_single_active
ON academic_period (is_active)
WHERE is_active = TRUE;


CREATE UNIQUE INDEX uq_student_specialty_active_primary
ON student_specialty (student_id)
WHERE selection_type = 'primary' AND is_active = TRUE;


CREATE UNIQUE INDEX uq_active_section_representative_position
ON section_representative (section_id, position)
WHERE is_active = TRUE;


CREATE UNIQUE INDEX uq_course_advising_session_course
ON course_advising_session (course_offering_id, teacher_id, day_of_week, start_time)
WHERE section_id IS NULL;


CREATE UNIQUE INDEX uq_course_advising_session_section
ON course_advising_session (section_id, teacher_id, day_of_week, start_time)
WHERE section_id IS NOT NULL;


CREATE UNIQUE INDEX uq_course_prerequisite_course
ON course_prerequisite (curriculum_course_id, prerequisite_curriculum_course_id)
WHERE prerequisite_curriculum_course_id IS NOT NULL;


CREATE UNIQUE INDEX uq_course_prerequisite_completed_cycle
ON course_prerequisite (curriculum_course_id, prerequisite_type, required_cycle)
WHERE required_cycle IS NOT NULL;


CREATE INDEX idx_student_user_id ON student (user_id);
CREATE INDEX idx_student_curriculum_id ON student (curriculum_id);
CREATE INDEX idx_curriculum_course_curriculum ON curriculum_course (curriculum_id);
CREATE INDEX idx_course_prerequisite_curriculum_course ON course_prerequisite (curriculum_course_id);
CREATE INDEX idx_course_offering_period ON course_offering (academic_period_id);
CREATE INDEX idx_section_course_offering ON section (course_offering_id);
CREATE INDEX idx_enrollment_student ON enrollment (student_id);
CREATE INDEX idx_schedule_session_section ON schedule_session (section_id);
CREATE INDEX idx_course_advising_session_course_offering ON course_advising_session (course_offering_id);
CREATE INDEX idx_assessment_syllabus ON assessment (syllabus_id);
CREATE INDEX idx_student_score_enrollment ON student_score (enrollment_id);
CREATE INDEX idx_alert_student ON alert (student_id);

